name: AurynCats.us
favicon: null
layout_spectrum: 0.50147
typography_spectrum: 0.6702391488943249
title: The Coons of Auryn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e48c22'
    - '#eda738'
    - '#8a3c0c'
    - '#d06f11'
    - '#d34f0e'
  brandStrength: 0.5
  lightness: 0.005972428014501929
  saturation: 0
  rhythmicContrast: 0.46989082358777523
purpose: []
